### ISSUE TITLE
'VFXCodeGenerator' already contains a definition for 'OnGenerateCode' Error

### ISSUE THREAD

**Issue by Xanduffy** [fluviofx/fluviofx#47]
Hey, I'm brand new to trying out Fluvio and pretty new to Unity VFX overall so excuse me if I'm missing something obvious, but I haven't been able to add the package successfully to my project. After installing the package and running Tools>FluvioFX>Install to clear the protection level errors, I am left with a single error message:

Library\PackageCache\com.unity.visualeffectgraph@12.1.2\Editor\Compiler\VFXCodeGenerator.cs(797,76): error CS0102: The type 'VFXCodeGenerator' already contains a definition for 'OnGenerateCode'

I can see the problem, that the following is repeated on line 742 and 797:
        // START FluvioFX
        public static event Func<VFXContext, StringBuilder, StringBuilder> OnGenerateCode;
        // END FluvioFX
However making any change, even commenting out the second instance of the line causes the VFXCodeGenerator to completely revert to before the Fluvio install, bringing back the protection level errors and requiring Tools>FluvioFX>Install to be run again to return to the single error. I don't know enough about Unity backend code to go any further and I haven't seen any specific answers in Unity forums or the previous issues here.

I'm using URP in 2021.2.7, I really hope somebody can help me out!

**Comment by ShockWave2048** [comment]
Same error. Can somebody help with this?

**Comment by mjducharme** [comment]
The official repo only supports up to Unity 2019.2. I've been able to update it myself to work with Unity 2020.3. See https://github.com/fluviofx/fluviofx/issues/29

**Comment by lmontoute** [comment]
Closing this - See #29 for progress on Unity version updates!
